# Generated by Django 5.0.4 on 2024-07-05 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_item_address_alter_item_email_alter_item_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='address',
        ),
    ]
